### ISSUE TITLE
Account Package 관련 코드 리뷰 및 이슈

### ISSUE THREAD

**Issue by bigquann97** [bigquann97/philosopher-back#160]
https://github.com/bigquann97/philosopher-back/blob/5f5ddf68248db379edc6fb1be7153cf69b11d80e/src/main/java/gladiator/philosopher/account/controller/AccountController.java#L40-L44

GetMapping에 불필요한 () 제거해주셔도 될 것 같습니다.

https://github.com/bigquann97/philosopher-back/blob/5f5ddf68248db379edc6fb1be7153cf69b11d80e/src/main/java/gladiator/philosopher/account/controller/AccountController.java#L59-L107

닉네임, 패스워드, 이미지를 별도의 프로필 변경 3가지 별도로 두어야하는지 궁금합니다.
하나의 api 로 뭉쳐서 profileModifyRequest로 두면 되지 않을까 싶습니다.
@ResponseStatus에 대한 고민도 필요하다고 생각합니다.
또한, PatchMapping이 아닌 PutMapping 으로 일부자원에 대한 변경을 요청해야할 것 같으며,
별도의 api 로 둔다고 해도 /nickname, /password, /image 로 api 를 명세해야할 것 같습니다.

https://github.com/bigquann97/philosopher-back/blob/6406cfc3b91c24eea25853ae5cc3d2b1d213f19d/src/main/java/gladiator/philosopher/account/dto/login/SignInRequestDto.java#L11

NoArgsConstructor 사용시 force 는 true 로 두지만 accessLevel을 private으로 두어 안정성을 높여주시기 바랍니다.

https://github.com/bigquann97/philosopher-back/blob/6406cfc3b91c24eea25853ae5cc3d2b1d213f19d/src/main/java/gladiator/philosopher/account/dto/AccountCommentDto.java#L12-L13

Response인지, Request인지 dto의 역할을 명확히 네이밍 해주시기 바랍니다.
또한, NoArgsConstructor의 경우, 다른 곳에서 빈 데이터가 생성될 수 있으므로 사용을 지양해주시기바랍니다.

https://github.com/bigquann97/philosopher-back/blob/6406cfc3b91c24eea25853ae5cc3d2b1d213f19d/src/main/java/gladiator/philosopher/account/dto/AccountSearchCondition.java#L5

@Data 애너테이션 적용시, Setter 같은 안정성에 불필요한 애너테이션이 포함되어있으므로 ,필요한 애너테이션만 사용하는 것을 권장드립니다.

https://github.com/bigquann97/philosopher-back/blob/6406cfc3b91c24eea25853ae5cc3d2b1d213f19d/src/main/java/gladiator/philosopher/account/entity/Account.java#L25-L28

다른 entity와 동일하게, 따로 account_id 로 컬럼 네임을 주지말고, 그대로 id 네이밍을 사용하면 될 것 같습니다.

https://github.com/bigquann97/philosopher-back/blob/6406cfc3b91c24eea25853ae5cc3d2b1d213f19d/src/main/java/gladiator/philosopher/account/entity/Account.java#L39-L40

nickname에도 unique 옵션을 줘도 될 것 같습니다.

https://github.com/bigquann97/philosopher-back/blob/6406cfc3b91c24eea25853ae5cc3d2b1d213f19d/src/main/java/gladiator/philosopher/account/entity/Account.java#L46-L48

userRole 타입에 대한 변수명으로 role을 사용하는 것이 좋을 것 같습니다.

https://github.com/bigquann97/philosopher-back/blob/6406cfc3b91c24eea25853ae5cc3d2b1d213f19d/src/main/java/gladiator/philosopher/account/entity/Account.java#L100-L106

메서드명은 첫글자 소문자로 변경 부탁드립니다.

https://github.com/bigquann97/philosopher-back/blob/6406cfc3b91c24eea25853ae5cc3d2b1d213f19d/src/main/java/gladiator/philosopher/account/entity/AccountInfo.java#L12-L15

NoArgs의 경우, Protected나 private으로 접근을 제어해주시고,
image에 대한 정보만 담고있다면, accountInfo 보다는 AccountImage로 네이밍하는 것이 맞을 것 같습니다.

https://github.com/bigquann97/philosopher-back/blob/6406cfc3b91c24eea25853ae5cc3d2b1d213f19d/src/main/java/gladiator/philosopher/account/repository/AccountRepository.java#L20-L24

불필요한 공백 제거 부탁드립니다.

https://github.com/bigquann97/philosopher-back/blob/6406cfc3b91c24eea25853ae5cc3d2b1d213f19d/src/main/java/gladiator/philosopher/account/service/AccountService.java#L30

메서드명 첫글자 소문자 부탁드립니다.

https://github.com/bigquann97/philosopher-back/blob/6406cfc3b91c24eea25853ae5cc3d2b1d213f19d/src/main/java/gladiator/philosopher/account/service/AccountServiceImpl.java#L37-L39

해당 서비스 클래스 내에서만 사용되는 메서드의 경우, private 하게 접근제어하여 다른 클래스에서 접근이 불가능하도록 하는 것이 안정성에 더 좋을 것 같습니다.

**Comment by jipang9** [comment]
1번 불필요한 () 제거  - 완료  
2. 이미지 - nickname, password 로 분리하겠습니다.
3. adminCheck()메서드 같은 경우엔 분명히 다른 곳에서 사용하려고 만들어 놓은 것이라, 사용처 생각해보고 사용도록 하겠습니다.

**Comment by bigquann97** [comment]
확인했습니다 2번 문제 해결되면 해당 이슈 닫도록하겠습니다.
3번 문제도 메서드명 첫글자 소문자로 변경 부탁드립니다.

**Comment by bigquann97** [comment]
해당 로직사항 반영된 것 확인했고 이슈 닫도록 하겠습니다.
