### ISSUE TITLE
Auth Package 관련 코드 리뷰 및 이슈

### ISSUE THREAD

**Issue by bigquann97** [bigquann97/philosopher-back#161]
https://github.com/bigquann97/philosopher-back/blob/6406cfc3b91c24eea25853ae5cc3d2b1d213f19d/src/main/java/gladiator/philosopher/auth/controller/AuthController.java#L29-L30

해당 변수들 사용하지 않는 것으로 보입니다. 삭제 필요할 것 같습니다.

https://github.com/bigquann97/philosopher-back/blob/6406cfc3b91c24eea25853ae5cc3d2b1d213f19d/src/main/java/gladiator/philosopher/auth/service/AuthService.java#L12-L17

불필요한 주석 제거 필요할 것 같습니다.

https://github.com/bigquann97/philosopher-back/blob/6406cfc3b91c24eea25853ae5cc3d2b1d213f19d/src/main/java/gladiator/philosopher/auth/service/AuthServiceImpl.java#L49

어플리케이션 내에서 어떤 이름을 default_image로 사용하고있는지 보안을 위해 숨길 필요가 있을 것 같습니다.
yml 파일을 통해 값을 주입받는 식으로 사용해야 될 것 같습니다.

https://github.com/bigquann97/philosopher-back/blob/6406cfc3b91c24eea25853ae5cc3d2b1d213f19d/src/main/java/gladiator/philosopher/auth/service/AuthServiceImpl.java#L58-L71

불필요한 공백 제거해야할 것 같습니다.

https://github.com/bigquann97/philosopher-back/blob/6406cfc3b91c24eea25853ae5cc3d2b1d213f19d/src/main/java/gladiator/philosopher/auth/service/AuthServiceImpl.java#L132-L145
CustomException을 뱉어내도록 해야할 것 같습니다.
key 값이나 value 값에 대해 hard coding 보다는 변수 선언을 통해 값을 넣어주어야 할 것 같습니다.

https://github.com/bigquann97/philosopher-back/blob/6406cfc3b91c24eea25853ae5cc3d2b1d213f19d/src/main/java/gladiator/philosopher/auth/service/EmailService.java#L26-L27

불필요한 주석 제거 필요할 것 같습니다.

https://github.com/bigquann97/philosopher-back/blob/6406cfc3b91c24eea25853ae5cc3d2b1d213f19d/src/main/java/gladiator/philosopher/auth/service/EmailService.java#L41
customException을 통해 원하는 값을 뱉어내야합니다.

**Comment by jipang9** [comment]
불필요한 주석 및 코드 수정 완료했습니다.  우선 관호님 요청사항대로 yml 파일을 이용해서 주입받는 방식으로 바꿨고,  예외처리 같은경우엔 커스텀예외처리로  바꿨습니다.

**Comment by bigquann97** [comment]
확인했습니다. 관련 코드 리뷰 후 문제 없으면 이슈 닫도록 하겠습니다.

**Comment by bigquann97** [comment]
해당 이슈 관련 디테일 잡을게 있어서 PR 올려두었습니다. 확인부탁드립니다.
