### ISSUE TITLE
Comment Package 관련 코드 리뷰 및 이슈

### ISSUE THREAD

**Issue by bigquann97** [bigquann97/philosopher-back#164]
https://github.com/bigquann97/philosopher-back/blob/6406cfc3b91c24eea25853ae5cc3d2b1d213f19d/src/main/java/gladiator/philosopher/comment/dto/CommentRequestDto.java#L10

NoArgs 사용시 force 및 accessLevel Private 으로 안정성을 보장해야할 것 같습니다.

https://github.com/bigquann97/philosopher-back/blob/6406cfc3b91c24eea25853ae5cc3d2b1d213f19d/src/main/java/gladiator/philosopher/comment/dto/CommentResponseDto.java#L16

NoArgs 사용시 force 및 accessLevel Private 으로 안정성을 보장해야할 것 같습니다.

https://github.com/bigquann97/philosopher-back/blob/6406cfc3b91c24eea25853ae5cc3d2b1d213f19d/src/main/java/gladiator/philosopher/comment/entity/Comment.java#L27

NoArgs 사용시 force 및 accessLevel Private 으로 안정성을 보장해야할 것 같습니다.

https://github.com/bigquann97/philosopher-back/blob/6406cfc3b91c24eea25853ae5cc3d2b1d213f19d/src/main/java/gladiator/philosopher/comment/entity/Comment.java#L39-L45

LazyLoading을 통해 불필요자원이 소모되지 않도록 방지하는 것이 좋을 것 같습니다.

https://github.com/bigquann97/philosopher-back/blob/6406cfc3b91c24eea25853ae5cc3d2b1d213f19d/src/main/java/gladiator/philosopher/comment/entity/Comment.java#L82-L84

어떤 동작을 하는 메서드인지 명확히 네이밍해야할 것 같습니다.
changeStatusToDeleted 같은 메서드명 사용이 좋을 것 같습니다.

https://github.com/bigquann97/philosopher-back/blob/6406cfc3b91c24eea25853ae5cc3d2b1d213f19d/src/main/java/gladiator/philosopher/comment/repository/CommentRepository.java#L20

불필요한 언더스코어 사용 제거해야할 것 같습니다.

https://github.com/bigquann97/philosopher-back/blob/6406cfc3b91c24eea25853ae5cc3d2b1d213f19d/src/main/java/gladiator/philosopher/comment/service/CommentServiceImpl.java#L78-L88

delete 를 직접 진행하는 것이 아닌, status 변경을 통해 softDeleteion 을 진행해야할 것 같습니다.

https://github.com/bigquann97/philosopher-back/blob/6406cfc3b91c24eea25853ae5cc3d2b1d213f19d/src/main/java/gladiator/philosopher/comment/service/CommentServiceImpl.java#L97-L102

comment.get 을 하는 것이 아닌, dto.get 을 해야 정보변경이 이루어집니다.

**Comment by jipang9** [comment]
comment delete 관련 논의는 조금 더 필요할 것 같아서 우선 수정하지 않았습니다

**Comment by bigquann97** [comment]
확인했습니다. Mention 관련 이슈로 인해 어떻게할지 생각해보겠습니다.
