### ISSUE TITLE
Post Package 관련 코드 리뷰 및 이슈

### ISSUE THREAD

**Issue by bigquann97** [bigquann97/philosopher-back#167]
https://github.com/bigquann97/philosopher-back/blob/6406cfc3b91c24eea25853ae5cc3d2b1d213f19d/src/main/java/gladiator/philosopher/post/controller/PostController.java#L61

변수명 첫글자 소문자로 변경 부탁드립니다.

https://github.com/bigquann97/philosopher-back/blob/6406cfc3b91c24eea25853ae5cc3d2b1d213f19d/src/main/java/gladiator/philosopher/post/controller/PostController.java#L75

pathVariable 명과 변수 명 동일할경우, @PathVariable 에 따로 옵션 주지 않아도 자동으로 매칭됩니다.
소괄호 제거 가능할 것 같습니다.

https://github.com/bigquann97/philosopher-back/blob/6406cfc3b91c24eea25853ae5cc3d2b1d213f19d/src/main/java/gladiator/philosopher/post/controller/PostController.java#L86

불필요한 슬래시 제거 부탁드립니다. - 소괄호 전부 없애주면 될 것 같습니다.

https://github.com/bigquann97/philosopher-back/blob/6406cfc3b91c24eea25853ae5cc3d2b1d213f19d/src/main/java/gladiator/philosopher/post/controller/PostController.java#L111-L134

해결된 부분이라면 주석 제거 필요해보입니다. 만약 해결되지 않았을 경우, 댓글로 계속해서 의견 나누시는걸로 하시죵

https://github.com/bigquann97/philosopher-back/blob/6406cfc3b91c24eea25853ae5cc3d2b1d213f19d/src/main/java/gladiator/philosopher/post/dto/PostModifyRequestDto.java#L7

force 및 accesslevel 안정성 높여주시기 바랍니다

https://github.com/bigquann97/philosopher-back/blob/6406cfc3b91c24eea25853ae5cc3d2b1d213f19d/src/main/java/gladiator/philosopher/post/dto/PostRequestDto.java#L13

accesLevel 제어 부탁드립니다.

https://github.com/bigquann97/philosopher-back/blob/6406cfc3b91c24eea25853ae5cc3d2b1d213f19d/src/main/java/gladiator/philosopher/post/dto/PostRequestDto.java#L39

EXCEEDED_INPUT_DATAS 같은 에러 변수명이 필요해보입니다.

https://github.com/bigquann97/philosopher-back/blob/6406cfc3b91c24eea25853ae5cc3d2b1d213f19d/src/main/java/gladiator/philosopher/post/dto/PostResponseDto.java#L16

ResponseDto의 경우 NoArgs 옵션 불필요합니다.

https://github.com/bigquann97/philosopher-back/blob/6406cfc3b91c24eea25853ae5cc3d2b1d213f19d/src/main/java/gladiator/philosopher/post/dto/PostResponseDtoByQueryDsl.java#L6

@Data 애너테이션보다는, 필요한 애너테이션만 사용하는 것이 좋아보입니다.

https://github.com/bigquann97/philosopher-back/blob/6406cfc3b91c24eea25853ae5cc3d2b1d213f19d/src/main/java/gladiator/philosopher/post/entity/Post.java#L44-L45

opinions 또한 양방향 연관관계를 제거해도 될 것 같은데 의견 남겨주시면 감사하겠습니다. @jipang9 

https://github.com/bigquann97/philosopher-back/blob/6406cfc3b91c24eea25853ae5cc3d2b1d213f19d/src/main/java/gladiator/philosopher/post/entity/Post.java#L37

ManyToOne의 기본 fetchType은 EAGER로 따로 명시하지 않아도 될 것 같습니다. 아니면 안정성을 위해 LAZY로 변경해도 좋을 것 같습니다.

https://github.com/bigquann97/philosopher-back/blob/6406cfc3b91c24eea25853ae5cc3d2b1d213f19d/src/main/java/gladiator/philosopher/post/entity/Post.java#L102-L104

메서드명 첫 글자 소문자로 변경 부탁드립니다. 또한, 어떤 행위인지 알 수 있는 메서드명 선정 부탁드립니다.
chnageStatusToDeleted 같은 이름이 적당할 것 같습니다. - 의견 남겨주세용

https://github.com/bigquann97/philosopher-back/blob/6406cfc3b91c24eea25853ae5cc3d2b1d213f19d/src/main/java/gladiator/philosopher/post/entity/PostImage.java#L28

ManyToOne에 대한 기본옵션 EAGER는 명시 안해도 될것같습니다. 혹은 LAZY로 변경하여 image가 불릴시 자동으로 post에 대한 정보가 불리지않도록 해야할 것 같습니다 - 의견 필요합니다.
cascade type에 대한 부분도 고민이 필요해보입니다.

https://github.com/bigquann97/philosopher-back/blob/6406cfc3b91c24eea25853ae5cc3d2b1d213f19d/src/main/java/gladiator/philosopher/post/entity/PostOpinion.java#L18
따로 table 명시해주지 않아도 해당 테이블 명 자동으로 선정됩니다.

https://github.com/bigquann97/philosopher-back/blob/6406cfc3b91c24eea25853ae5cc3d2b1d213f19d/src/main/java/gladiator/philosopher/post/repository/PostRepository.java#L16-L25

불필요 주석일 경우 삭제 부탁드립니다.

https://github.com/bigquann97/philosopher-back/blob/6406cfc3b91c24eea25853ae5cc3d2b1d213f19d/src/main/java/gladiator/philosopher/post/service/PostService.java#L20-L38

불필요한 주석 제거 부탁드리며, 메서드당 줄 간격 유지 부탁드립니다.

https://github.com/bigquann97/philosopher-back/blob/6406cfc3b91c24eea25853ae5cc3d2b1d213f19d/src/main/java/gladiator/philosopher/post/service/PostServiceImpl.java#L95-L111

final 키워드 추가 부탁드립니다. - 이 외에도 다른 메서드에 대한 final 키워드 추가 부탁드립니다.

https://github.com/bigquann97/philosopher-back/blob/6406cfc3b91c24eea25853ae5cc3d2b1d213f19d/src/main/java/gladiator/philosopher/post/service/PostServiceImpl.java#L174-L179

Transactional 옵션 추가 필요해보입니다.

https://github.com/bigquann97/philosopher-back/blob/6406cfc3b91c24eea25853ae5cc3d2b1d213f19d/src/main/java/gladiator/philosopher/post/service/PostServiceImpl.java#L197-L210

Transactional 옵션 추가 필요해보입니다.

**Comment by jipang9** [comment]
1. 우선 Pathvariable 같은 경우엔 좀 더 정확하게 매칭하기 위해 해당 값을 명시해줬습니다. 또한 코드처럼 명시적으로 나타내는 경우엔 가독성도 증가한다 생각해서 우선 제거하지 않았습니다. 

2. 게시글의 생성 시점에서 opnions는 거의 필수적인 요소입니다. 그래서 post 입장에서는 양방향 관계를 통해서 options 를 무조건 가지고 있어야 한다고 생각합니다. 

3. 메서드명 변경 같은 경우엔 관호님 말씀대로 조금 더 명확한 행위를 나타내는 말로 바꾸는 것이 옳다고 생각했고, 어떻게 나타낼 수 있을까 라는 생각을 했었는데, 관호님이 주신 의견대로 반영토록 하겠습니다.

**Comment by bigquann97** [comment]
@jipang9 
opnions가 필수요소이긴 하지만, 해당 값을 변수로 무조건 갖고있으면서 양방향을 맺는것과는 다른 맥락같습니다. 
관심을 갖는지 갖지 않는지의 여부에따라 양방향 연관관계의 유무가 결정되어야한다 생각합니다.
post.getOpinions() 를 꼭 사용해야할 이유가 있을 경우에 맺는 것이 맞다고생각합니다.

**Comment by jipang9** [comment]
> @jipang9 opnions가 필수요소이긴 하지만, 해당 값을 변수로 무조건 갖고있으면서 양방향을 맺는것과는 다른 맥락같습니다. 관심을 갖는지 갖지 않는지의 여부에따라 양방향 연관관계의 유무가 결정되어야한다 생각합니다. post.getOpinions() 를 꼭 사용해야할 이유가 있을 경우에 맺는 것이 맞다고생각합니다.

일단 관련 내용 인지했고, 정답이 있는 부분이 아니라서 우선 성능을 체크해보고, 이후 결정도록 하겠습니다!

**Comment by bigquann97** [comment]
해당 이슈 완료로 닫겠습니다
