### ISSUE TITLE
Report Package 관련 코드 리뷰 및 이슈

### ISSUE THREAD

**Issue by bigquann97** [bigquann97/philosopher-back#169]
https://github.com/bigquann97/philosopher-back/blob/6406cfc3b91c24eea25853ae5cc3d2b1d213f19d/src/main/java/gladiator/philosopher/report/controller/ReportController.java#L30-L37

ResponseStatus 명시 필요해보입니다.

https://github.com/bigquann97/philosopher-back/blob/6406cfc3b91c24eea25853ae5cc3d2b1d213f19d/src/main/java/gladiator/philosopher/report/dto/post/PostReportResponseDto.java#L12-L16

불필요 스페이스바 제거 부탁드립니다.

https://github.com/bigquann97/philosopher-back/blob/6406cfc3b91c24eea25853ae5cc3d2b1d213f19d/src/main/java/gladiator/philosopher/report/dto/post/PostReportResponseDto.java#L9

Response 의 경우 noArgs 불필요합니다.

https://github.com/bigquann97/philosopher-back/blob/6406cfc3b91c24eea25853ae5cc3d2b1d213f19d/src/main/java/gladiator/philosopher/report/repository/PostReportRepository.java#L17-L18

메서드명 변경 필요해보입니다.
getAllPostReportDtosByAdmin 같은 메서드명이 좋아보입니다.

**Comment by jipang9** [comment]
확인 후 수정 완료했습니다.

**Comment by bigquann97** [comment]
PR 확인 부탁드립니다.
