### ISSUE TITLE
Thread Package 관련 코드 리뷰 및 이슈

### ISSUE THREAD

**Issue by bigquann97** [bigquann97/philosopher-back#171]
https://github.com/bigquann97/philosopher-back/blob/6406cfc3b91c24eea25853ae5cc3d2b1d213f19d/src/main/java/gladiator/philosopher/thread/controller/ThreadController.java#L28-L36

별도의 Scheduler 패키지 및 클래스파일을 두어 관리가 필요할 것 같습니다.

https://github.com/bigquann97/philosopher-back/blob/6406cfc3b91c24eea25853ae5cc3d2b1d213f19d/src/main/java/gladiator/philosopher/thread/dto/ThreadResponseDto.java#L11

Response의 경우 NoArgs 애너테이션 불필요합니다.

https://github.com/bigquann97/philosopher-back/blob/6406cfc3b91c24eea25853ae5cc3d2b1d213f19d/src/main/java/gladiator/philosopher/thread/dto/ThreadSearchCond.java#L13

NoArgs 불필요해보입니다.

https://github.com/bigquann97/philosopher-back/blob/6406cfc3b91c24eea25853ae5cc3d2b1d213f19d/src/main/java/gladiator/philosopher/thread/dto/ThreadSimpleResponseDto.java#L12

NoArgs 불필요해보입니다.

https://github.com/bigquann97/philosopher-back/blob/6406cfc3b91c24eea25853ae5cc3d2b1d213f19d/src/main/java/gladiator/philosopher/thread/entity/Thread.java#L97-L112

EqualsAndHashCode 위로 메서드 위치 변경 부탁드립니다.

https://github.com/bigquann97/philosopher-back/blob/6406cfc3b91c24eea25853ae5cc3d2b1d213f19d/src/main/java/gladiator/philosopher/thread/repository/ThreadRepository.java#L20-L24

불필요 주석이라면 제거 부탁드립니다.

https://github.com/bigquann97/philosopher-back/blob/6406cfc3b91c24eea25853ae5cc3d2b1d213f19d/src/main/java/gladiator/philosopher/thread/service/ThreadServiceImpl.java#L102

readonly true

https://github.com/bigquann97/philosopher-back/blob/6406cfc3b91c24eea25853ae5cc3d2b1d213f19d/src/main/java/gladiator/philosopher/thread/service/ThreadServiceImpl.java#L115

readonly true

https://github.com/bigquann97/philosopher-back/blob/6406cfc3b91c24eea25853ae5cc3d2b1d213f19d/src/main/java/gladiator/philosopher/thread/service/ThreadServiceImpl.java#L128

readonly true

https://github.com/bigquann97/philosopher-back/blob/6406cfc3b91c24eea25853ae5cc3d2b1d213f19d/src/main/java/gladiator/philosopher/thread/service/ThreadServiceImpl.java#L185-L191

Long 값 따로 사용하지 않는다면 return type 없애도 될 것 같습니다.

**Comment by jipang9** [comment]
일단 아직 이 부분들을 수정하진 않았는데 Long 값을 리턴한 이유는 나중에 해당 서비스 로직이 실행되고 최종 반환되는 프론트 단에서 해당 게시물에 관한 Id로 get 요청을 할 예정입니다. 그래서 사용자가 페이지를 수정 후 리다이렉트 받는 방식으로 id를 채택했습니다.

**Comment by bigquann97** [comment]
확인했습니당

**Comment by bigquann97** [comment]
해당 파트 제가 수정 맡도록 하겠습니다. 말씀해주신 부분 반영해서 리팩터링 진행하겠습니다.

**Comment by bigquann97** [comment]
Scheduler 관련해서 이슈 새로 파서 진행하도록 하겠습니다. 이 이슈는 닫도록 하겠습니다.
