### ISSUE TITLE
Comment 작성 오류

### ISSUE THREAD

**Issue by dohwapark** [bigquann97/philosopher-back#193]
Comment content 값을 숫자로만 받으면 String index out of range 라는 오류 발생
MentionService 관련 문제로 보여짐

**Comment by bigquann97** [comment]
숫자만 적을시 발생하는 오류 해결하겠습니다!

**Comment by bigquann97** [comment]
이 외에도, 첫줄에 대해서만 맨션을 extract 했었는데, content의 모든 내용에 대한 mention을 extract 하도록 수정하겠습니다
