### ISSUE TITLE
accountInfo : 내 정보 조회 시 이미지 데이터 추가

### ISSUE THREAD

**Issue by jipang9** [bigquann97/philosopher-back#199]

**Comment by bigquann97** [comment]
Post Response DTO 시에도 사용자 image url 응답값에 포함시키는 작업 진행 가능하신가여

**Comment by jipang9** [comment]
> l

추가해서 작업 하겠ㅅ습니다.

**Comment by jipang9** [comment]
> s

아마 post ResponseDto 호출 시 자신의 ImageUrl까지 가지고오도록 되어 있습니다.
