### ISSUE TITLE
쓰레드 조회시 가장 많은 좋아요를 받은 의견별 댓글 조회 api

### ISSUE THREAD

**Issue by bigquann97** [bigquann97/philosopher-back#212]
쓰레드 조회시 가장 많은 좋아요를 받은 의견별 댓글 조회 api

**Comment by bigquann97** [comment]
가장 많은 좋아요를 상위 3개 출력할 것인지, 의견별 최상위 좋아요 받은 댓글 출력한 것인지 고민중입니다

**Comment by bigquann97** [comment]
[
    {
        "id": 1,
        "content": "내용",
        "nickname": "김지환",
        "imageUrl": "jipang1.jpg",
        "likeCount": 3
    },
    {
        "id": 2,
        "content": "내용",
        "nickname": "박정수",
        "imageUrl": "https://the-gladiators.s3.ap-northeast-2.amazonaws.com/AccountImg/cbf685ea-6cb2-4448-872d-0e503a7eddddimage",
        "likeCount": 2
    }
]

좋아요의 경우 - 상위 3개의 좋아요 노출 - 3개 안채워질시 따로 값 뱉지 않음

**Comment by bigquann97** [comment]
[
    {
        "opinion": "의견1",
        "ratio": 18
    },
    {
        "opinion": "의견2",
        "ratio": 54
    },
    {
        "opinion": "의견3",
        "ratio": 27
    }
]

통계의 경우, ratio 노출로 비율 확인 - 의견에 대한 비율 없을시 값 뱉지 않음

**Comment by jipang9** [comment]
> 가장 많은 좋아요를 상위 3개 출력할 것인지, 의견별 최상위 좋아요 받은 댓글 출력한 것인지 고민중입니다

제 생각엔 가장 많은 좋아요 상위 3개를 노출하는 것이 좋아보입니다.
