### ISSUE TITLE
admin -스케쥴러 이용해서 매일 정시에 신고 10개 이상인 사람은 자동으로 suspended 상태로 만들기

### ISSUE THREAD

**Issue by jipang9** [bigquann97/philosopher-back#218]

**Comment by bigquann97** [comment]
매일 정시에 SUSPENDED 를 동작시킬지, 아니면 신고 로직이 발생할때마다 해당 유저에 대한 신고 수를 체크해서 SUSPENDED 상태로 만들것인지에 대한 고민이 필요해보입니다.

**Comment by bigquann97** [comment]
그리고 유저를 SUSPENDED 시킬 예정인가요? 아직 게시글/쓰레드/댓글에 대해서만 BLINDED 처리만 구현된 상태이긴 합니다.
SUSPENDED 시킨다면, 어떤 방식으로 해당 유저의 접근을 막을 예정이신가요.

**Comment by jipang9** [comment]
> 매일 정시에 SUSPENDED 를 동작시킬지, 아니면 신고 로직이 발생할때마다 해당 유저에 대한 신고 수를 체크해서 SUSPENDED 상태로 만들것인지에 대한 고민이 필요해보입니다.

일단 24시간 운영진이 상주하면서 신고 관련해서 유저를 확인할 수 없다고 생각해서 매일 정시에 동작을 시켜야겠다 라고 생각을 했습니다. 그리고 신고 로직이 발생할 때마다 만약에 해당 유저에 관한 신고 로직을 체크하게 된다면 또한 db에 무리가 가지 않을까 라는 생각이 듭니다. 그래서 이 신고 관련해서 로직처리를 우선 admin에 의한 관리부분 하나랑 스케쥴러를 이용한 매일 정시 체크 이렇게 2가지로 가지고 감이 좋지 않을까? 라는 생각을 했습니다. 

누군가 죄없는 사람을 악의적으로 신고했을 때, 자동으로 상태가 처리되거나, 그렇게 된다면 좀 억울할 것 같아서 관리자의 판단과 스케쥴러를 생각해봤습니다.

**Comment by jipang9** [comment]
> 그리고 유저를 SUSPENDED 시킬 예정인가요? 아직 게시글/쓰레드/댓글에 대해서만 BLINDED 처리만 구현된 상태이긴 합니다. SUSPENDED 시킨다면, 어떤 방식으로 해당 유저의 접근을 막을 예정이신가요.

아마 만약에 유저를 suspended 시키게 된다면 새로운 role 하나가 추가될 것 같습니다 (user의 하위버전), 그래서 각 컨트롤러 단에서 접근 자체를 막아버리는 생각이 들었습니다.  그래서 유저 role로 관리하게되면 기존의 로직들은 크게 변경되는게 없고, 컨트롤러 단에서만 처리를 해준다면 편하게 구현이 가능하지 않을ㄲ ㅏ생각됩니다.

**Comment by jipang9** [comment]
> 매일 정시에 SUSPENDED 를 동작시킬지, 아니면 신고 로직이 발생할때마다 해당 유저에 대한 신고 수를 체크해서 SUSPENDED 상태로 만들것인지에 대한 고민이 필요해보입니다.

이거 관련해서 다른 의견이나 생각있으시면 언제든지 말씀해주시면 고려해보겠습니다.
