### ISSUE TITLE
[금쪽 같은 내 코드] Comment <=> Mention 정보 긁어오기 관련 이슈

### ISSUE THREAD

**Issue by bigquann97** [bigquann97/philosopher-back#222]
https://github.com/bigquann97/philosopher-back/blob/3dbce8287295fcacc1df68104d8a51cdd23ea1e6/src/main/java/gladiator/philosopher/comment/entity/Comment.java#L45-L49

현재 Comment Entity 는 해당 객체가 어떤 댓글을 Mention 하고 있는지, 어떤 댓글로부터 Mention 받고있는지에 대해 정보를 양방향 연관관계로 맺고있습니다.

https://github.com/bigquann97/philosopher-back/blob/3dbce8287295fcacc1df68104d8a51cdd23ea1e6/src/main/java/gladiator/philosopher/comment/dto/CommentResponseDto.java#L10-L61

그래서, Comment 를 Response dto 로 작성할 때, 그에 대한 정보도 긁어와야 되다보니 다음과 같이 Comment 전체 객체를 긁어와서 해당 정보를 dto에 주입하는 방식으로 사용하고 있습니다.

https://github.com/bigquann97/philosopher-back/blob/3dbce8287295fcacc1df68104d8a51cdd23ea1e6/src/main/java/gladiator/philosopher/comment/dto/MentionResponseDto.java#L5-L21

Mention Response Dto의 경우, 해당 멘션 커멘트의 id는 무엇인지, content는 무엇인지 뿌려주고 있습니다.

그에 대한 결과로, 다음과 같이
```
        {
            "commentId": 128,
            "nickname": "이정국",
            "opinion": "안한다.",
            "content": "#125 #127 하하",
            "createDate": "2023-02-27 15:53",
            "status": "ACTIVE",
            "recommendCount": 0,
            "mentioningComments": [
                {
                    "id": 125,
                    "content": "content"
                },
                {
                    "id": 127,
                    "content": "content"
                }
            ],
            "mentionedComments": [
                {
                    "id": 129,
                    "content": "#128 하하"
                }
            ],
            "imageUrl": "jipang3.jpg"
        },
``` 
해당 댓글이 몇번 댓글을 멘션하고 있는지와 그 댓글의 내용, 몇번 댓글에 대해 멘션당하고 있는지와 그 댓글의 내용이 노출되게 됩니다.

그런데, 여기서 쿼리 최적화와 관련된 이슈가 발생합니다.

https://github.com/bigquann97/philosopher-back/blob/3dbce8287295fcacc1df68104d8a51cdd23ea1e6/src/main/java/gladiator/philosopher/comment/repository/CommentCustomRepositoryImpl.java#L40-L72

현재 다음과 같이 쿼리문을 짜둔 상태입니다.
해당 댓글 엔티티 전체와, comment 에 대한 좋아요 카운트, 코멘트작성자의 imgUrl 세개를 한번에 긁어오는 쿼리를 작성했는데,
해당 댓글의 멘션 정보가 몇개이든 한 페이지 내에 무조건 출력해주어야할 것이라고 생각해 쿼리를 짜긴 했는데,

해당 쿼리 발생시, 멘션 정보를 긁어오기 위해 Mention/Mentioned 와 관련해 각 10번의 쿼리 (총20번 - 페이징시 10개의 댓글을 긁어옴) 이 발생하게 되고, 불필요한 정보를 긁어오고 있습니다. 

아직까지는 @BatchSize를 통해 OneToMany 로 지정한 Set 을 불러올때 적당량을 퍼올리는 방식을 구상하고 있기는한데, 어떤 식으로 해당 문제를 해결해야할지 감이 잘 잡히지 않습니다. 

만약 쿼리를 분리한다면, Comment 단건 조회라면 가능할 것 같지만, 10건을 페이징 조회하는데, 각 comment에 대해서 어떻게 해당 정보를 주입할지에 대한 고민도 있습니다.

고민 들어주셔서 감사합니다!

**Comment by thesun4sky** [comment]
- mentioningComments, mentionedComments 조회하는 부분을 stream으로 조회하다보니 개별쿼리가 발생한것이기 때문에, 이를 해결하기 위해 mentioningComments, mentionedComments 요 2개를 따로 쿼리메소드로 정의하고 페이지내에 commentID 목록으로 In절 쿼리를 각각 만들어서 Map<Key,Value> 형태로 조회해온 뒤에 (여기서 key는 commentId, Value 는 mentioningComments(id,content) 또는mentionedComments(id,content) 이걸 후주입 시켜주는 방식으로 해결 가능할것 같습니다.
