### ISSUE TITLE
Comment 관련 코드 리뷰

### ISSUE THREAD

**Issue by bigquann97** [bigquann97/philosopher-back#54]
Comments 를 작성하면서 기억해야할 점은 post 엔 comment가 없고 유일한 연관관계는 comment => thread 관계가 있다는 점 입니다.

1. https://github.com/bigquann97/philosopher-back/blob/dcb659b210bf84eade2b2becba948e1ec0da6c26/src/main/java/gladiator/philosopher/comment/controller/CommentController.java#L32-L36
url 관련 이슈입니다.
post는 comment 객체가 없기도 하고(comment API에서 불필요한 정보입니다), 
comment API 를 작성해야 한다는 점에 초점을 두어 작성이 가능합니다.
`/api/comments?thread-id=3`  혹은 `/api/comments?id=3` 만으로도
3번 id의 comments를 조회한다는 사실을 알 수 있습니다. post는 필요 없는 정보 입니다.

2. https://github.com/bigquann97/philosopher-back/blob/dcb659b210bf84eade2b2becba948e1ec0da6c26/src/main/java/gladiator/philosopher/comment/controller/CommentController.java#L66-L74
댓글 수정시에도, 몇번 포스트의 몇번 쓰레드의 몇번 댓글인지 확인할 필요가 없습니다.
몇번 쓰레드에 대한 댓글인지 또한 필요없는 정보입니다. 
클라이언트 쪽에서 정보를 확인할때, 게시글이나 댓글에 대한 정보는 모른 상태로 댓글에 대한 요청을 시도하기 때문에
댓글 id 만을 통해 해당 댓글에 대해 접근이 가능해야합니다.
`/api/comments/{commentId} - ex) /api/comments/3` 과 같이 표현 가능합니다.

하지만, 여기서 댓글 삭제를 요청하는 유저가 누구인지에 대한 정보는 필요합니다. - 해당 유저가 아닐경우 삭제가 되면 안되기 때문에
따라서, 여기서 service 에 넘겨줄 정보는 account, commendId, commentRequestDto 정도밖에 없겠네요.

3. https://github.com/bigquann97/philosopher-back/blob/dcb659b210bf84eade2b2becba948e1ec0da6c26/src/main/java/gladiator/philosopher/comment/controller/CommentController.java#L85-L91
저희 조는 ResponseEntity 를 통해 상태코드와 body를 출력하는 것 말고,
메서드 위에 `@ResponseStatus(Status.OK)` 처럼 상태코드를 출력해주기로 했고,
return  에는 순수 객체(만을 담아 메서드를 작성하기로 하였습니다.
그리고, 등록/수정/삭제에 대해서는 사용자에게 어떤 body 를 전달해주지 않아도(return 타입 void) 상태코드만을 통해 등록/수정/삭제 등이 잘 이루어졌는지 확인할 수 있습니다. 그래서 return 타입은 void로 해주어도 무방합니다.

**Comment by bigquann97** [comment]
https://github.com/bigquann97/philosopher-back/blob/dcb659b210bf84eade2b2becba948e1ec0da6c26/src/main/java/gladiator/philosopher/comment/service/CommentServiceImpl.java#L33-L34
Post 객체에 대한 정보는 불필요합니다!

**Comment by bigquann97** [comment]
https://github.com/bigquann97/philosopher-back/blob/dcb659b210bf84eade2b2becba948e1ec0da6c26/src/main/java/gladiator/philosopher/comment/service/CommentServiceImpl.java#L65-L88
해당 로직은 comment를 수정하는 것이 아닌 comment 를 새로 생성하는 로직처럼 보입니다.
Comment 객체 내부에, 자기 값들을 변경하는 메서드를 두어
comment.ModifyComment(dto.getContent) 와 같이 어떻게 정보를 수정할 것인지에 대해 작성해주세용

또한, id 값을 바탕으로 찾아온 comment 안에 있는 account 정보가 - 정보를 요청한 memberDetails.getMember() 랑 일치하는지 확인하는 로직이 필요할 것 같습니다 - 즉, 댓글 수정을 요청한 계정 정보와 comment 작성 계정이 일치하는지에 대한 정보가 일치해야하는 로직

**Comment by bigquann97** [comment]
https://github.com/bigquann97/philosopher-back/blob/dcb659b210bf84eade2b2becba948e1ec0da6c26/src/main/java/gladiator/philosopher/comment/service/CommentServiceImpl.java#L90-L97
불필요한 정보는 안받아도 되고(thread id, post id 등등)
윗 댓글과 마찬가지로 요청자와 게시글작성자가 일치하는지에 대한 로직이 필요합니다.

**Comment by h7359841** [comment]
> Comments 를 작성하면서 기억해야할 점은 post 엔 comment가 없고 유일한 연관관계는 comment => thread 관계가 있다는 점 입니다.
> 
> 1. https://github.com/bigquann97/philosopher-back/blob/dcb659b210bf84eade2b2becba948e1ec0da6c26/src/main/java/gladiator/philosopher/comment/controller/CommentController.java#L32-L36
>    
>    url 관련 이슈입니다.
>    post는 comment 객체가 없기도 하고(comment API에서 불필요한 정보입니다),
>    comment API 를 작성해야 한다는 점에 초점을 두어 작성이 가능합니다.
>    `/api/comments?thread-id=3`  혹은 `/api/comments?id=3` 만으로도
>    3번 id의 comments를 조회한다는 사실을 알 수 있습니다. post는 필요 없는 정보 입니다.
--------------------------------------------------------------------------------------------------------------------------------------------
> https://github.com/bigquann97/philosopher-back/blob/dcb659b210bf84eade2b2becba948e1ec0da6c26/src/main/java/gladiator/philosopher/comment/entity/Comment.java#L32-L34
> 
> 
> 위와 같은 이유로 Comment 는 Post 객체를 가질 필요가 없습니다.
--------------------------------------------------------------------------------------------------------------------------------------------
> https://github.com/bigquann97/philosopher-back/blob/dcb659b210bf84eade2b2becba948e1ec0da6c26/src/main/java/gladiator/philosopher/comment/service/CommentServiceImpl.java#L33-L34
> 
> 
> Post 객체에 대한 정보는 불필요합니다!
--------------------------------------------------------------------------------------------------------------------------------------------
A.
댓글 관련 이슈에서 위 이슈들은(3/7) <댓글 로직 수정 - Post와 연관되는 부분 제외 #53> 을 통해 수정하였습니다. 이후 수정 사항은 밑에 계속 추가하도록 하겠습니다.
